//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public interface I_InputReceiver
	{
		//Methods to be called when attached or detached to sender class
		void onAttachedToSender();
		void onDetachFromSender();

		//Mathods to treat each input
		//Pressing is binary (no intermediate jumping values), 
		//so we don't need the Axis values

		//Each implementor needs to decide whether they care
		//About a certain input or not
		void onButtonPressed(E_InputTypes type);
		void onButtonReleased(E_InputTypes type);
	}
}

