//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class AIStateMachine
	{
		//Class Fields
		private GameObject owner;
		private I_AIState currentState;
		private I_AIState previousState;
		private I_AIState globalState;

		//Constructor
		public AIStateMachine (GameObject owner)
		{
			this.owner = owner;
		}

		//Initializers
		public void setCurrentState(I_AIState s) {this.currentState = s;}
		public void setGlobalState(I_AIState s) {this.globalState = s;}
		public void setPrevState(I_AIState s) {this.previousState = s;}

		//Main function to update
		public void Update() {
			if (this.globalState != null) {
				this.globalState.onExecute (owner);
			}

			if (this.currentState != null) {
				this.currentState.onExecute(owner);
			}
		}

		//Method called by states to change state
		public void changeState(I_AIState s) {
			this.previousState = this.currentState;
			this.currentState.onExit (owner);
			this.currentState = (s);
			this.currentState.onEnter (owner);
		}

	}
}

